// Generated by tools/build_cards.py. Do not edit by hand.
window.BINDER_DATA = window.BINDER_DATA || {};
window.BINDER_DATA["shinji kanda"] = {
 "artist": "Shinji Kanda",
 "cards": [
  {
   "id": "swshp-SWSH185",
   "name": "Moltres",
   "set": "SWSH Black Star Promos",
   "number": "SWSH185",
   "rarity": "Promo",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/swshp/SWSH185_hires.png",
    "https://images.pokemontcg.io/swshp/SWSH185.png",
    "https://assets.tcgdex.net/ja/S/S12a/190/high.webp",
    "https://assets.tcgdex.net/ja/S/S12a/190/high.png"
   ]
  },
  {
   "id": "swshp-SWSH284",
   "name": "Galarian Moltres",
   "set": "SWSH Black Star Promos",
   "number": "SWSH284",
   "rarity": "Promo",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/swshp/SWSH284_hires.png",
    "https://images.pokemontcg.io/swshp/SWSH284.png",
    "https://assets.tcgdex.net/en/swsh/swshp/SWSH284/high.webp",
    "https://assets.tcgdex.net/en/swsh/swshp/SWSH284/high.png",
    "https://assets.tcgdex.net/ja/S/S12a/190/high.webp",
    "https://assets.tcgdex.net/ja/S/S12a/190/high.png"
   ]
  },
  {
   "id": "swsh9-19",
   "aliases": [
    "swsh9-019"
   ],
   "name": "Magmar",
   "set": "Brilliant Stars",
   "number": "19",
   "rarity": "Common",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/swsh9/19_hires.png",
    "https://images.pokemontcg.io/swsh9/19.png",
    "https://assets.tcgdex.net/en/swsh/swsh9/019/high.webp",
    "https://assets.tcgdex.net/en/swsh/swsh9/019/high.png",
    "https://assets.tcgdex.net/ja/S/S12a/016/high.webp",
    "https://assets.tcgdex.net/ja/S/S12a/016/high.png",
    "https://assets.tcgdex.net/ja/S/S9/016/high.webp",
    "https://assets.tcgdex.net/ja/S/S9/016/high.png"
   ]
  },
  {
   "id": "swsh9-81",
   "aliases": [
    "swsh9-081"
   ],
   "name": "Sawk",
   "set": "Brilliant Stars",
   "number": "81",
   "rarity": "Common",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/swsh9/81_hires.png",
    "https://images.pokemontcg.io/swsh9/81.png",
    "https://assets.tcgdex.net/en/swsh/swsh9/081/high.webp",
    "https://assets.tcgdex.net/en/swsh/swsh9/081/high.png",
    "https://assets.tcgdex.net/ja/S/S9/057/high.webp",
    "https://assets.tcgdex.net/ja/S/S9/057/high.png"
   ]
  },
  {
   "id": "swsh10-36",
   "aliases": [
    "swsh10-036"
   ],
   "name": "Whiscash",
   "set": "Astral Radiance",
   "number": "36",
   "rarity": "Uncommon",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/swsh10/36_hires.png",
    "https://images.pokemontcg.io/swsh10/36.png",
    "https://assets.tcgdex.net/en/swsh/swsh10/036/high.webp",
    "https://assets.tcgdex.net/en/swsh/swsh10/036/high.png",
    "https://assets.tcgdex.net/ja/S/S9a/022/high.webp",
    "https://assets.tcgdex.net/ja/S/S9a/022/high.png"
   ]
  },
  {
   "id": "swsh10-112",
   "name": "Bronzong",
   "set": "Astral Radiance",
   "number": "112",
   "rarity": "Uncommon",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/swsh10/112_hires.png",
    "https://images.pokemontcg.io/swsh10/112.png",
    "https://assets.tcgdex.net/en/swsh/swsh10/112/high.webp",
    "https://assets.tcgdex.net/en/swsh/swsh10/112/high.png",
    "https://assets.tcgdex.net/ja/S/S10P/049/high.webp",
    "https://assets.tcgdex.net/ja/S/S10P/049/high.png"
   ]
  },
  {
   "id": "swsh11-113",
   "name": "Ariados",
   "set": "Lost Origin",
   "number": "113",
   "rarity": "Rare",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/swsh11/113_hires.png",
    "https://images.pokemontcg.io/swsh11/113.png",
    "https://assets.tcgdex.net/en/swsh/swsh11/113/high.webp",
    "https://assets.tcgdex.net/en/swsh/swsh11/113/high.png"
   ]
  },
  {
   "id": "swsh11-186",
   "name": "Giratina V",
   "set": "Lost Origin",
   "number": "186",
   "rarity": "Rare Ultra",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/swsh11/186_hires.png",
    "https://images.pokemontcg.io/swsh11/186.png",
    "https://assets.tcgdex.net/en/swsh/swsh11/186/high.webp",
    "https://assets.tcgdex.net/en/swsh/swsh11/186/high.png",
    "https://assets.tcgdex.net/ja/S/S11/111/high.webp",
    "https://assets.tcgdex.net/ja/S/S11/111/high.png"
   ]
  },
  {
   "id": "swsh12-55",
   "aliases": [
    "swsh12-055"
   ],
   "name": "Stunfisk",
   "set": "Silver Tempest",
   "number": "55",
   "rarity": "Common",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/swsh12/55_hires.png",
    "https://images.pokemontcg.io/swsh12/55.png",
    "https://assets.tcgdex.net/en/swsh/swsh12/055/high.webp",
    "https://assets.tcgdex.net/en/swsh/swsh12/055/high.png",
    "https://assets.tcgdex.net/ja/S/S12/029/high.webp",
    "https://assets.tcgdex.net/ja/S/S12/029/high.png"
   ]
  },
  {
   "id": "swsh12-61",
   "aliases": [
    "swsh12-061"
   ],
   "name": "Hypno",
   "set": "Silver Tempest",
   "number": "61",
   "rarity": "Uncommon",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/swsh12/61_hires.png",
    "https://images.pokemontcg.io/swsh12/61.png",
    "https://assets.tcgdex.net/en/swsh/swsh12/061/high.webp",
    "https://assets.tcgdex.net/en/swsh/swsh12/061/high.png",
    "https://assets.tcgdex.net/ja/S/S11/043/high.webp",
    "https://assets.tcgdex.net/ja/S/S11/043/high.png"
   ]
  },
  {
   "id": "swsh12-80",
   "aliases": [
    "swsh12-080"
   ],
   "name": "Beheeyem",
   "set": "Silver Tempest",
   "number": "80",
   "rarity": "Uncommon",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/swsh12/80_hires.png",
    "https://images.pokemontcg.io/swsh12/80.png",
    "https://assets.tcgdex.net/en/swsh/swsh12/080/high.webp",
    "https://assets.tcgdex.net/en/swsh/swsh12/080/high.png",
    "https://assets.tcgdex.net/ja/S/S12/044/high.webp",
    "https://assets.tcgdex.net/ja/S/S12/044/high.png"
   ]
  },
  {
   "id": "svp-159",
   "name": "Magneton",
   "set": "SVP Black Star Promos",
   "number": "159",
   "rarity": "Promo",
   "game": "TCG",
   "images": [
    "https://assets.tcgdex.net/en/sv/svp/159/high.webp",
    "https://assets.tcgdex.net/en/sv/svp/159/high.png",
    "https://assets.tcgdex.net/ja/SV/SV8/112/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV8/112/high.png"
   ]
  },
  {
   "id": "sv1-43",
   "aliases": [
    "sv01-043"
   ],
   "name": "Slowbro",
   "set": "Scarlet & Violet",
   "number": "43",
   "rarity": "Rare",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/sv1/43_hires.png",
    "https://images.pokemontcg.io/sv1/43.png",
    "https://assets.tcgdex.net/en/sv/sv01/043/high.webp",
    "https://assets.tcgdex.net/en/sv/sv01/043/high.png",
    "https://assets.tcgdex.net/ja/SV/SV1V/020/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV1V/020/high.png",
    "https://assets.tcgdex.net/ja/SV/SV4a/037/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV4a/037/high.png"
   ]
  },
  {
   "id": "sv1-48",
   "aliases": [
    "sv01-048"
   ],
   "name": "Alomomola",
   "set": "Scarlet & Violet",
   "number": "48",
   "rarity": "Common",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/sv1/48_hires.png",
    "https://images.pokemontcg.io/sv1/48.png",
    "https://assets.tcgdex.net/en/sv/sv01/048/high.webp",
    "https://assets.tcgdex.net/en/sv/sv01/048/high.png"
   ]
  },
  {
   "id": "sv2-203",
   "aliases": [
    "sv02-203"
   ],
   "name": "Magikarp",
   "set": "Paldea Evolved",
   "number": "203",
   "rarity": "Illustration Rare",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/sv2/203_hires.png",
    "https://images.pokemontcg.io/sv2/203.png",
    "https://assets.tcgdex.net/en/sv/sv02/203/high.webp",
    "https://assets.tcgdex.net/en/sv/sv02/203/high.png",
    "https://assets.tcgdex.net/ja/M/M6a/165/high.webp",
    "https://assets.tcgdex.net/ja/M/M6a/165/high.png",
    "https://assets.tcgdex.net/ja/SV/SV1a/080/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV1a/080/high.png"
   ]
  },
  {
   "id": "sv3-144",
   "aliases": [
    "sv03-144"
   ],
   "name": "Bronzor",
   "set": "Obsidian Flames",
   "number": "144",
   "rarity": "Common",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/sv3/144_hires.png",
    "https://images.pokemontcg.io/sv3/144.png",
    "https://assets.tcgdex.net/en/sv/sv03/144/high.webp",
    "https://assets.tcgdex.net/en/sv/sv03/144/high.png",
    "https://assets.tcgdex.net/ja/SV/SV2P/050/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV2P/050/high.png"
   ]
  },
  {
   "id": "sv3pt5-142",
   "aliases": [
    "sv03.5-142"
   ],
   "name": "Aerodactyl",
   "set": "151",
   "number": "142",
   "rarity": "Rare",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/sv3pt5/142_hires.png",
    "https://images.pokemontcg.io/sv3pt5/142.png",
    "https://assets.tcgdex.net/en/sv/sv03.5/142/high.webp",
    "https://assets.tcgdex.net/en/sv/sv03.5/142/high.png",
    "https://assets.tcgdex.net/ja/SV/SV2a/142/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV2a/142/high.png"
   ]
  },
  {
   "id": "sv4-62",
   "aliases": [
    "sv04-062"
   ],
   "name": "Blitzle",
   "set": "Paradox Rift",
   "number": "62",
   "rarity": "Common",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/sv4/62_hires.png",
    "https://images.pokemontcg.io/sv4/62.png",
    "https://assets.tcgdex.net/en/sv/sv04/062/high.webp",
    "https://assets.tcgdex.net/en/sv/sv04/062/high.png",
    "https://assets.tcgdex.net/ja/SV/SV4M/023/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV4M/023/high.png"
   ]
  },
  {
   "id": "sv4-113",
   "aliases": [
    "sv04-113"
   ],
   "name": "Absol",
   "set": "Paradox Rift",
   "number": "113",
   "rarity": "Uncommon",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/sv4/113_hires.png",
    "https://images.pokemontcg.io/sv4/113.png",
    "https://assets.tcgdex.net/en/sv/sv04/113/high.webp",
    "https://assets.tcgdex.net/en/sv/sv04/113/high.png",
    "https://assets.tcgdex.net/ja/SV/SV3a/036/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV3a/036/high.png"
   ]
  },
  {
   "id": "sv5-43",
   "aliases": [
    "sv05-043"
   ],
   "name": "Sharpedo",
   "set": "Temporal Forces",
   "number": "43",
   "rarity": "Uncommon",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/sv5/43_hires.png",
    "https://images.pokemontcg.io/sv5/43.png",
    "https://assets.tcgdex.net/en/sv/sv05/043/high.webp",
    "https://assets.tcgdex.net/en/sv/sv05/043/high.png",
    "https://assets.tcgdex.net/ja/M/MC/179/high.webp",
    "https://assets.tcgdex.net/ja/M/MC/179/high.png",
    "https://assets.tcgdex.net/ja/SV/SV5K/017/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV5K/017/high.png"
   ]
  },
  {
   "id": "sv6-83",
   "aliases": [
    "sv06-083"
   ],
   "name": "Girafarig",
   "set": "Twilight Masquerade",
   "number": "83",
   "rarity": "Common",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/sv6/83_hires.png",
    "https://images.pokemontcg.io/sv6/83.png",
    "https://assets.tcgdex.net/en/sv/sv06/083/high.webp",
    "https://assets.tcgdex.net/en/sv/sv06/083/high.png",
    "https://assets.tcgdex.net/ja/M/MC/301/high.webp",
    "https://assets.tcgdex.net/ja/M/MC/301/high.png",
    "https://assets.tcgdex.net/ja/SV/SV5a/034/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV5a/034/high.png"
   ]
  },
  {
   "id": "sv6pt5-9",
   "aliases": [
    "sv06.5-009"
   ],
   "name": "Iron Moth",
   "set": "Shrouded Fable",
   "number": "9",
   "rarity": "Uncommon",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/sv6pt5/9_hires.png",
    "https://images.pokemontcg.io/sv6pt5/9.png",
    "https://assets.tcgdex.net/en/sv/sv06.5/009/high.webp",
    "https://assets.tcgdex.net/en/sv/sv06.5/009/high.png",
    "https://assets.tcgdex.net/ja/SV/SV6a/009/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV6a/009/high.png"
   ]
  },
  {
   "id": "sv6pt5-26",
   "aliases": [
    "sv06.5-026"
   ],
   "name": "Slither Wing",
   "set": "Shrouded Fable",
   "number": "26",
   "rarity": "Uncommon",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/sv6pt5/26_hires.png",
    "https://images.pokemontcg.io/sv6pt5/26.png",
    "https://assets.tcgdex.net/en/sv/sv06.5/026/high.webp",
    "https://assets.tcgdex.net/en/sv/sv06.5/026/high.png",
    "https://assets.tcgdex.net/ja/M/MC/423/high.webp",
    "https://assets.tcgdex.net/ja/M/MC/423/high.png",
    "https://assets.tcgdex.net/ja/SV/SV6a/026/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV6a/026/high.png",
    "https://assets.tcgdex.net/ja/SV/SV8a/087/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV8a/087/high.png"
   ]
  },
  {
   "id": "sv08-150",
   "name": "Kecleon",
   "set": "Surging Sparks",
   "number": "150",
   "rarity": "Common",
   "game": "TCG",
   "images": [
    "https://assets.tcgdex.net/en/sv/sv08/150/high.webp",
    "https://assets.tcgdex.net/en/sv/sv08/150/high.png",
    "https://assets.tcgdex.net/ja/SV/SV8/086/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV8/086/high.png"
   ]
  },
  {
   "id": "sv08.5-162",
   "name": "Roaring Moon ex",
   "set": "Prismatic Evolutions",
   "number": "162",
   "rarity": "Special illustration rare",
   "game": "TCG",
   "images": [
    "https://assets.tcgdex.net/en/sv/sv08.5/162/high.webp",
    "https://assets.tcgdex.net/en/sv/sv08.5/162/high.png"
   ]
  },
  {
   "id": "zsv10pt5-105",
   "aliases": [
    "sv10.5b-105"
   ],
   "name": "Seismitoad",
   "set": "Black Bolt",
   "number": "105",
   "rarity": "Illustration Rare",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/zsv10pt5/105_hires.png",
    "https://images.pokemontcg.io/zsv10pt5/105.png",
    "https://assets.tcgdex.net/en/sv/sv10.5b/105/high.webp",
    "https://assets.tcgdex.net/en/sv/sv10.5b/105/high.png",
    "https://assets.tcgdex.net/ja/SV/SV11B/109/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV11B/109/high.png"
   ]
  },
  {
   "id": "mep-024",
   "name": "Oricorio ex",
   "set": "MEP Black Star Promos",
   "number": "024",
   "rarity": "Promo",
   "game": "TCG",
   "images": [
    "https://assets.tcgdex.net/en/me/mep/024/high.webp",
    "https://assets.tcgdex.net/en/me/mep/024/high.png",
    "https://assets.tcgdex.net/ja/M/M2/111/high.webp",
    "https://assets.tcgdex.net/ja/M/M2/111/high.png"
   ]
  },
  {
   "id": "me01-068",
   "name": "Sandshrew",
   "set": "Mega Evolution",
   "number": "068",
   "rarity": "Common",
   "game": "TCG",
   "images": [
    "https://assets.tcgdex.net/en/me/me01/068/high.webp",
    "https://assets.tcgdex.net/en/me/me01/068/high.png",
    "https://assets.tcgdex.net/ja/M/M1L/020/high.webp",
    "https://assets.tcgdex.net/ja/M/M1L/020/high.png"
   ]
  },
  {
   "id": "me2-74",
   "aliases": [
    "me02-074"
   ],
   "name": "Duraludon",
   "set": "Phantasmal Flames",
   "number": "74",
   "rarity": "Common",
   "game": "TCG",
   "images": [
    "https://images.pokemontcg.io/me2/74_hires.png",
    "https://images.pokemontcg.io/me2/74.png",
    "https://assets.tcgdex.net/en/me/me02/074/high.webp",
    "https://assets.tcgdex.net/en/me/me02/074/high.png",
    "https://assets.tcgdex.net/ja/M/M2/062/high.webp",
    "https://assets.tcgdex.net/ja/M/M2/062/high.png"
   ]
  },
  {
   "id": "me03-014",
   "name": "Talonflame",
   "set": "Perfect Order",
   "number": "014",
   "rarity": "Uncommon",
   "game": "TCG",
   "images": [
    "https://assets.tcgdex.net/en/me/me03/014/high.webp",
    "https://assets.tcgdex.net/en/me/me03/014/high.png",
    "https://assets.tcgdex.net/ja/M/M3/014/high.webp",
    "https://assets.tcgdex.net/ja/M/M3/014/high.png"
   ]
  },
  {
   "id": "ja-M6-046",
   "name": "Sableye",
   "set": "ストームエメラルダ (Japan)",
   "number": "046",
   "rarity": "Common",
   "game": "TCG (Japan)",
   "images": [
    "https://assets.tcgdex.net/ja/M/M6/046/high.webp",
    "https://assets.tcgdex.net/ja/M/M6/046/high.png"
   ]
  },
  {
   "id": "me55-40",
   "aliases": [
    "30th-040"
   ],
   "name": "Pikachu",
   "set": "30th Celebration",
   "number": "40",
   "rarity": "Pikachu Rare",
   "game": "TCG",
   "images": [
    "https://images.scrydex.com/pokemon/me55-40/large",
    "https://images.scrydex.com/pokemon/me55-40/small",
    "https://assets.tcgdex.net/en/me/30th/040/high.webp",
    "https://assets.tcgdex.net/en/me/30th/040/high.png",
    "https://assets.tcgdex.net/ja/M/M6a/034/high.webp",
    "https://assets.tcgdex.net/ja/M/M6a/034/high.png"
   ]
  },
  {
   "id": "me55c-203",
   "aliases": [
    "30th-c-030"
   ],
   "name": "Magikarp",
   "set": "30th Classic Collection",
   "number": "203",
   "rarity": "Illustration Rare",
   "game": "TCG",
   "images": [
    "https://images.scrydex.com/pokemon/me55c-203/large",
    "https://images.scrydex.com/pokemon/me55c-203/small",
    "https://assets.tcgdex.net/en/me/30th-c/030/high.webp",
    "https://assets.tcgdex.net/en/me/30th-c/030/high.png",
    "https://assets.tcgdex.net/ja/M/M6a/165/high.webp",
    "https://assets.tcgdex.net/ja/M/M6a/165/high.png",
    "https://assets.tcgdex.net/ja/SV/SV1a/080/high.webp",
    "https://assets.tcgdex.net/ja/SV/SV1a/080/high.png"
   ]
  },
  {
   "id": "A2-172",
   "name": "Spiritomb",
   "set": "Space-Time Smackdown",
   "number": "172",
   "rarity": "One Star",
   "game": "Pocket",
   "images": [
    "https://assets.tcgdex.net/en/tcgp/A2/172/high.webp",
    "https://assets.tcgdex.net/en/tcgp/A2/172/high.png"
   ]
  },
  {
   "id": "A2b-096",
   "name": "Giratina ex",
   "set": "Shining Revelry",
   "number": "096",
   "rarity": "Three Star",
   "game": "Pocket",
   "images": [
    "https://assets.tcgdex.net/en/tcgp/A2b/096/high.webp",
    "https://assets.tcgdex.net/en/tcgp/A2b/096/high.png"
   ]
  },
  {
   "id": "A3-176",
   "name": "Drampa",
   "set": "Celestial Guardians",
   "number": "176",
   "rarity": "One Star",
   "game": "Pocket",
   "images": [
    "https://assets.tcgdex.net/en/tcgp/A3/176/high.webp",
    "https://assets.tcgdex.net/en/tcgp/A3/176/high.png"
   ]
  },
  {
   "id": "A3b-039",
   "name": "Whiscash",
   "set": "Eevee Grove",
   "number": "039",
   "rarity": "Two Diamond",
   "game": "Pocket",
   "images": [
    "https://assets.tcgdex.net/en/tcgp/A3b/039/high.webp",
    "https://assets.tcgdex.net/en/tcgp/A3b/039/high.png"
   ]
  },
  {
   "id": "A4-111",
   "name": "Ariados",
   "set": "Wisdom of Sea and Sky",
   "number": "111",
   "rarity": "Two Diamond",
   "game": "Pocket",
   "images": [
    "https://assets.tcgdex.net/en/tcgp/A4/111/high.webp",
    "https://assets.tcgdex.net/en/tcgp/A4/111/high.png"
   ]
  },
  {
   "id": "A4-207",
   "name": "Crobat ex",
   "set": "Wisdom of Sea and Sky",
   "number": "207",
   "rarity": "Two Star",
   "game": "Pocket",
   "images": [
    "https://assets.tcgdex.net/en/tcgp/A4/207/high.webp",
    "https://assets.tcgdex.net/en/tcgp/A4/207/high.png"
   ]
  },
  {
   "id": "B1-281",
   "name": "Dragalge ex",
   "set": "Mega Rising",
   "number": "281",
   "rarity": "Two Star",
   "game": "Pocket",
   "images": [
    "https://assets.tcgdex.net/en/tcgp/B1/281/high.webp",
    "https://assets.tcgdex.net/en/tcgp/B1/281/high.png"
   ]
  }
 ]
};
