// Generated by tools/build_artofpkm.py. Do not edit by hand.
window.BINDER_DATA = window.BINDER_DATA || {};
window.BINDER_DATA["shinji kanda"] = {
 "artist": "Shinji Kanda",
 "source": "https://www.artofpkm.com/illustrators/shinji-kanda/cards",
 "cards": [
  {
   "id": "apkm-592-34",
   "name": "Pikachu",
   "set": "30th CELEBRATION",
   "number": "034/103",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/592/card/34",
   "thumb": "https://cdn.artofpkm.com/v9ihnycpagqlsneh01awicec54a3",
   "images": [
    "https://cdn.artofpkm.com/9hg32n8yl11rydrdhw0kwjdp46rc",
    "https://cdn.artofpkm.com/v9ihnycpagqlsneh01awicec54a3"
   ],
   "aliases": [
    "me55-40",
    "30th-040"
   ]
  },
  {
   "id": "apkm-592-165",
   "name": "Magikarp",
   "set": "30th CELEBRATION",
   "number": "165/103",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/592/card/165",
   "thumb": "https://cdn.artofpkm.com/s14pra7lpigi8it4wf0yfmo16n6a",
   "images": [
    "https://cdn.artofpkm.com/w99tz194bgugccb8hp7665ma64os",
    "https://cdn.artofpkm.com/s14pra7lpigi8it4wf0yfmo16n6a"
   ],
   "aliases": [
    "me55c-203",
    "30th-c-030"
   ]
  },
  {
   "id": "apkm-595-46",
   "name": "Sableye",
   "set": "Storm Emeralda",
   "number": "046/076",
   "rarity": "Common",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/595/card/46",
   "thumb": "https://cdn.artofpkm.com/uitad6e4qb8foj63tlmcttz5ipgp",
   "images": [
    "https://cdn.artofpkm.com/ko5e8mmwwr0sub7rdgjh40ijc3gd",
    "https://cdn.artofpkm.com/uitad6e4qb8foj63tlmcttz5ipgp"
   ],
   "aliases": [
    "ja-M6-046"
   ]
  },
  {
   "id": "apkm-583-14",
   "name": "Talonflame",
   "set": "Nihil Zero",
   "number": "014/080",
   "rarity": "Uncommon",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/583/card/14",
   "thumb": "https://cdn.artofpkm.com/ctgtj10i4zvuyronq0x7hyhj7hz0",
   "images": [
    "https://cdn.artofpkm.com/rlcic5pgdioxvmow9ysh8oivby3c",
    "https://cdn.artofpkm.com/ctgtj10i4zvuyronq0x7hyhj7hz0"
   ],
   "aliases": [
    "me03-014"
   ]
  },
  {
   "id": "apkm-581-214",
   "name": "Sharpedo",
   "set": "Start Deck 100 Battle Collection",
   "number": "179/742",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/581/card/214",
   "thumb": "https://cdn.artofpkm.com/szxhy2czljn7lrjku9ymne8si6um",
   "images": [
    "https://cdn.artofpkm.com/ahh0lhchfdpyjhl2d7yk9pfmz9r9",
    "https://cdn.artofpkm.com/szxhy2czljn7lrjku9ymne8si6um"
   ]
  },
  {
   "id": "apkm-581-358",
   "name": "Girafarig",
   "set": "Start Deck 100 Battle Collection",
   "number": "301/742",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/581/card/358",
   "thumb": "https://cdn.artofpkm.com/f1xeokrxq8l0iedqyoeau458l1vs",
   "images": [
    "https://cdn.artofpkm.com/o9nm27s83kr3hmhqlwkwigi5d18f",
    "https://cdn.artofpkm.com/f1xeokrxq8l0iedqyoeau458l1vs"
   ]
  },
  {
   "id": "apkm-581-489",
   "name": "Slither Wing",
   "set": "Start Deck 100 Battle Collection",
   "number": "423/742",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/581/card/489",
   "thumb": "https://cdn.artofpkm.com/2z6s18itatbfjyl6yx491d6ym07b",
   "images": [
    "https://cdn.artofpkm.com/27f2pu78rn5ptrj7a1229fi00bp9",
    "https://cdn.artofpkm.com/2z6s18itatbfjyl6yx491d6ym07b"
   ]
  },
  {
   "id": "apkm-575-62",
   "name": "Duraludon",
   "set": "Inferno X",
   "number": "062/080",
   "rarity": "Common",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/575/card/62",
   "thumb": "https://cdn.artofpkm.com/4cor3ishdpqhlncoljl3nx2eluud",
   "images": [
    "https://cdn.artofpkm.com/msoveueekp31yts4j0xxw3igb4t4",
    "https://cdn.artofpkm.com/4cor3ishdpqhlncoljl3nx2eluud"
   ],
   "aliases": [
    "me2-74",
    "me02-074"
   ]
  },
  {
   "id": "apkm-575-111",
   "name": "Oricorio ex",
   "set": "Inferno X",
   "number": "111/080",
   "rarity": "Special Art Rare",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/575/card/111",
   "thumb": "https://cdn.artofpkm.com/x7dhp5syyrrs4duc20vdjydd0ndw",
   "images": [
    "https://cdn.artofpkm.com/m3dyqowzhi5op2gdfitaq77d593o",
    "https://cdn.artofpkm.com/x7dhp5syyrrs4duc20vdjydd0ndw"
   ],
   "aliases": [
    "mep-024"
   ]
  },
  {
   "id": "apkm-570-20",
   "name": "Sandshrew",
   "set": "Mega Brave",
   "number": "020/063",
   "rarity": "Common",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/570/card/20",
   "thumb": "https://cdn.artofpkm.com/zb5n3d953p57o68behisbi9sfm0w",
   "images": [
    "https://cdn.artofpkm.com/7gcw61hsh04yzgl4nvun3zyp59w5",
    "https://cdn.artofpkm.com/zb5n3d953p57o68behisbi9sfm0w"
   ],
   "aliases": [
    "me01-068"
   ]
  },
  {
   "id": "apkm-565-189",
   "name": "Seismitoad",
   "set": "Black Bolt",
   "number": "109/086",
   "rarity": "Art Rare",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/565/card/189",
   "thumb": "https://cdn.artofpkm.com/bd6vpbxxmra6hndsxq41k3xj6a36",
   "images": [
    "https://cdn.artofpkm.com/kdy2y28iujm2l51kh8npvtyyh49l",
    "https://cdn.artofpkm.com/bd6vpbxxmra6hndsxq41k3xj6a36"
   ],
   "aliases": [
    "zsv10pt5-105",
    "sv10.5b-105"
   ]
  },
  {
   "id": "apkm-552-152",
   "name": "Slither Wing",
   "set": "Terastal Festival ex",
   "number": "087/187",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/552/card/152",
   "thumb": "https://cdn.artofpkm.com/og0ircuw4yeirm7qhvjomm0tuqnn",
   "images": [
    "https://cdn.artofpkm.com/9p7ykjl39anb38zanqh85id62fee",
    "https://cdn.artofpkm.com/og0ircuw4yeirm7qhvjomm0tuqnn"
   ]
  },
  {
   "id": "apkm-625-66",
   "name": "Slither Wing",
   "set": "Poké Ball Mirror",
   "number": "087/187",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/625/card/66",
   "thumb": "https://cdn.artofpkm.com/8uxhz0qejmp936m7n1dzsae32xx5",
   "images": [
    "https://cdn.artofpkm.com/y9nez6cilhswfbywj1rwhulhpvn0",
    "https://cdn.artofpkm.com/8uxhz0qejmp936m7n1dzsae32xx5"
   ]
  },
  {
   "id": "apkm-552-362",
   "name": "Roaring Moon ex",
   "set": "Terastal Festival ex",
   "number": "218/187",
   "rarity": "Special Art Rare",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/552/card/362",
   "thumb": "https://cdn.artofpkm.com/78m4cebcpe9bvxvpm72u4fj7euzp",
   "images": [
    "https://cdn.artofpkm.com/88agu98r481vpqzx4ck00zdnamf9",
    "https://cdn.artofpkm.com/78m4cebcpe9bvxvpm72u4fj7euzp"
   ],
   "aliases": [
    "sv08.5-162"
   ]
  },
  {
   "id": "apkm-551-86",
   "name": "Kecleon",
   "set": "Electric Breaker",
   "number": "086/106",
   "rarity": "Common",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/551/card/86",
   "thumb": "https://cdn.artofpkm.com/ltk8e3n9an9yzbapz7havqnjajrm",
   "images": [
    "https://cdn.artofpkm.com/h7umdej1izafgk6e2myu73d89ous",
    "https://cdn.artofpkm.com/ltk8e3n9an9yzbapz7havqnjajrm"
   ],
   "aliases": [
    "sv08-150"
   ]
  },
  {
   "id": "apkm-551-112",
   "name": "Magneton",
   "set": "Electric Breaker",
   "number": "112/106",
   "rarity": "Art Rare",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/551/card/112",
   "thumb": "https://cdn.artofpkm.com/1h8m2h4ad2uznvju3h95xhnwy1ec",
   "images": [
    "https://cdn.artofpkm.com/9vmt9zn7lyfqrdypzdig7sw6h9u7",
    "https://cdn.artofpkm.com/1h8m2h4ad2uznvju3h95xhnwy1ec"
   ],
   "aliases": [
    "svp-159"
   ]
  },
  {
   "id": "apkm-519-9",
   "name": "Iron Moth",
   "set": "Night Wanderer",
   "number": "009/064",
   "rarity": "Uncommon",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/519/card/9",
   "thumb": "https://cdn.artofpkm.com/xltwu6dk68z7b598rk12v8wl3gc6",
   "images": [
    "https://cdn.artofpkm.com/sgeb0fo408in52u60banzjb782d5",
    "https://cdn.artofpkm.com/xltwu6dk68z7b598rk12v8wl3gc6"
   ],
   "aliases": [
    "sv6pt5-9",
    "sv06.5-009"
   ]
  },
  {
   "id": "apkm-519-26",
   "name": "Slither Wing",
   "set": "Night Wanderer",
   "number": "026/064",
   "rarity": "Uncommon",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/519/card/26",
   "thumb": "https://cdn.artofpkm.com/n3qzm9w0m62rcek0q4dnsqf8wtdm",
   "images": [
    "https://cdn.artofpkm.com/p3p72ayn3utyielwvaob75bj79e1",
    "https://cdn.artofpkm.com/n3qzm9w0m62rcek0q4dnsqf8wtdm"
   ],
   "aliases": [
    "sv6pt5-26",
    "sv06.5-026"
   ]
  },
  {
   "id": "apkm-513-34",
   "name": "Girafarig",
   "set": "Crimson Haze",
   "number": "034/066",
   "rarity": "Common",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/513/card/34",
   "thumb": "https://cdn.artofpkm.com/gty9sso3gg1hhvdwcxmm65tpmcy6",
   "images": [
    "https://cdn.artofpkm.com/ha7j7ebrofs27r6ma8w6jccbo1sw",
    "https://cdn.artofpkm.com/gty9sso3gg1hhvdwcxmm65tpmcy6"
   ],
   "aliases": [
    "sv6-83",
    "sv06-083"
   ]
  },
  {
   "id": "apkm-508-17",
   "name": "Sharpedo",
   "set": "Wild Force",
   "number": "017/071",
   "rarity": "Uncommon",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/508/card/17",
   "thumb": "https://cdn.artofpkm.com/b803kyf7qi7adt56wkjrez6zd1j4",
   "images": [
    "https://cdn.artofpkm.com/o2rforerx59h5qcotv86ylvapdmi",
    "https://cdn.artofpkm.com/b803kyf7qi7adt56wkjrez6zd1j4"
   ],
   "aliases": [
    "sv5-43",
    "sv05-043"
   ]
  },
  {
   "id": "apkm-506-58",
   "name": "Slowbro",
   "set": "Shiny Treasure ex",
   "number": "037/190",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/506/card/58",
   "thumb": "https://cdn.artofpkm.com/x6e7yqykb73g2op5j79r6at1yfez",
   "images": [
    "https://cdn.artofpkm.com/ili3njx4hym9unbd3dg90i0vj9x7",
    "https://cdn.artofpkm.com/x6e7yqykb73g2op5j79r6at1yfez"
   ]
  },
  {
   "id": "apkm-505-17",
   "name": "Alomomola",
   "set": "Special Deck Set ex Venusaur, Charizard, & Blastoise",
   "number": "017/049",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/505/card/17",
   "thumb": "https://cdn.artofpkm.com/fq7lpklqmxln8l2w19cewntlzg7q",
   "images": [
    "https://cdn.artofpkm.com/duv2mgleu20u2qr5zdu8h4maffdx",
    "https://cdn.artofpkm.com/fq7lpklqmxln8l2w19cewntlzg7q"
   ]
  },
  {
   "id": "apkm-503-23",
   "name": "Blitzle",
   "set": "Future Flash",
   "number": "023/066",
   "rarity": "Common",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/503/card/23",
   "thumb": "https://cdn.artofpkm.com/fkjji4rxr7zrj4bvit56wl2pmkfi",
   "images": [
    "https://cdn.artofpkm.com/zbd58vua1iq77ezijxz9mvkwgcny",
    "https://cdn.artofpkm.com/fkjji4rxr7zrj4bvit56wl2pmkfi"
   ],
   "aliases": [
    "sv4-62",
    "sv04-062"
   ]
  },
  {
   "id": "apkm-502-36",
   "name": "Absol",
   "set": "Raging Surf",
   "number": "036/062",
   "rarity": "Uncommon",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/502/card/36",
   "thumb": "https://cdn.artofpkm.com/d20scvsuc784r9qktpoixhigh2m3",
   "images": [
    "https://cdn.artofpkm.com/p0gorgwen8d65mew5eayvyju48fb",
    "https://cdn.artofpkm.com/d20scvsuc784r9qktpoixhigh2m3"
   ],
   "aliases": [
    "sv4-113",
    "sv04-113"
   ]
  },
  {
   "id": "apkm-491-26",
   "name": "Alomomola",
   "set": "ex Start Decks",
   "number": "026/139",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/491/card/26",
   "thumb": "https://cdn.artofpkm.com/xxs0qnjhlkoyhplpd5w5xv1zg5zv",
   "images": [
    "https://cdn.artofpkm.com/j4ddjdrnstbusloq4g199tato4mw",
    "https://cdn.artofpkm.com/xxs0qnjhlkoyhplpd5w5xv1zg5zv"
   ]
  },
  {
   "id": "apkm-490-273",
   "name": "Aerodactyl",
   "set": "Pokémon Card 151",
   "number": "142/165",
   "rarity": "Rare",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/490/card/273",
   "thumb": "https://cdn.artofpkm.com/1rb8wcmx3g24uxbzg51g9d5cozpw",
   "images": [
    "https://cdn.artofpkm.com/nai3v4bb1lg8xtig7b4u94nyl8ff",
    "https://cdn.artofpkm.com/1rb8wcmx3g24uxbzg51g9d5cozpw"
   ],
   "aliases": [
    "sv3pt5-142",
    "sv03.5-142"
   ]
  },
  {
   "id": "apkm-624-132",
   "name": "Aerodactyl",
   "set": "Poké Ball Mirror",
   "number": "142/165",
   "rarity": "Rare",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/624/card/132",
   "thumb": "https://cdn.artofpkm.com/qli6izwpmgxt707www21l7pxrn50",
   "images": [
    "https://cdn.artofpkm.com/te7qv8b9qm2awxll5yfkzgv7oiew",
    "https://cdn.artofpkm.com/qli6izwpmgxt707www21l7pxrn50"
   ]
  },
  {
   "id": "apkm-484-50",
   "name": "Bronzor",
   "set": "Snow Hazard",
   "number": "050/071",
   "rarity": "Common",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/484/card/50",
   "thumb": "https://cdn.artofpkm.com/y82ffv227wd5e3m0i0ibasuxr16g",
   "images": [
    "https://cdn.artofpkm.com/uin3nrcrn9zxuphmvpeqqvlvb0qp",
    "https://cdn.artofpkm.com/y82ffv227wd5e3m0i0ibasuxr16g"
   ],
   "aliases": [
    "sv3-144",
    "sv03-144"
   ]
  },
  {
   "id": "apkm-485-80",
   "name": "Magikarp",
   "set": "Triplet Beat",
   "number": "080/073",
   "rarity": "Art Rare",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/485/card/80",
   "thumb": "https://cdn.artofpkm.com/xk6f95chiu42y3vuum5p142tjn55",
   "images": [
    "https://cdn.artofpkm.com/bwb6yll5j2rcp4hr23k8m260nttk",
    "https://cdn.artofpkm.com/xk6f95chiu42y3vuum5p142tjn55"
   ],
   "aliases": [
    "sv2-203",
    "sv02-203"
   ]
  },
  {
   "id": "apkm-541-1",
   "name": "Alomomola",
   "set": "Scarlet & Violet Starter set ex Quaxly & Mimikyu ex",
   "number": "001/023",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/541/card/1",
   "thumb": "https://cdn.artofpkm.com/akpu6so5lxol1v4o4x7zpp3x5ilu",
   "images": [
    "https://cdn.artofpkm.com/zjmi2xhd86oj14bgl2f4vkonjwq0",
    "https://cdn.artofpkm.com/akpu6so5lxol1v4o4x7zpp3x5ilu"
   ],
   "aliases": [
    "sv1-48",
    "sv01-048"
   ]
  },
  {
   "id": "apkm-482-20",
   "name": "Slowbro",
   "set": "Violet ex",
   "number": "020/078",
   "rarity": "Rare",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/482/card/20",
   "thumb": "https://cdn.artofpkm.com/jogl6vh0blxmqr16nokerks9zakc",
   "images": [
    "https://cdn.artofpkm.com/onagedqyjf4n4pj9tvycjh3jnde8",
    "https://cdn.artofpkm.com/jogl6vh0blxmqr16nokerks9zakc"
   ],
   "aliases": [
    "sv1-43",
    "sv01-043"
   ]
  },
  {
   "id": "apkm-479-24",
   "name": "Magmar",
   "set": "VSTAR Universe",
   "number": "016/172",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/479/card/24",
   "thumb": "https://cdn.artofpkm.com/gtzw9m8j6k4kd4pscksfy5yy3n1m",
   "images": [
    "https://cdn.artofpkm.com/amz0ozxxmqqhin4i0r76qsuhf78a",
    "https://cdn.artofpkm.com/gtzw9m8j6k4kd4pscksfy5yy3n1m"
   ]
  },
  {
   "id": "apkm-632-9",
   "name": "Magmar",
   "set": "Mirror",
   "number": "016/172",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/632/card/9",
   "thumb": "https://cdn.artofpkm.com/8r37cfkb2in03akvyxt28kbdmsup",
   "images": [
    "https://cdn.artofpkm.com/vg0d2j7byccnt8hmvldtxh07wubo",
    "https://cdn.artofpkm.com/8r37cfkb2in03akvyxt28kbdmsup"
   ]
  },
  {
   "id": "apkm-479-279",
   "name": "Galarian Moltres",
   "set": "VSTAR Universe",
   "number": "190/172",
   "rarity": "Art Rare",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/479/card/279",
   "thumb": "https://cdn.artofpkm.com/mzbr0ypqhnypy5yg6lz9hz3jjq4p",
   "images": [
    "https://cdn.artofpkm.com/hslszo8fyawpk6mr0sy0jdwpdpea",
    "https://cdn.artofpkm.com/mzbr0ypqhnypy5yg6lz9hz3jjq4p"
   ],
   "aliases": [
    "swshp-SWSH284"
   ]
  },
  {
   "id": "apkm-477-7",
   "name": "Moltres",
   "set": "Special Deck Set Charizard VSTAR vs Rayquaza VMAX",
   "number": "007/030",
   "rarity": "",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/477/card/7",
   "thumb": "https://cdn.artofpkm.com/neh6rgjtljhd5262m0pyilvftpt0",
   "images": [
    "https://cdn.artofpkm.com/yy0vfhz1pa8yr9gs29q8ir6nh67t",
    "https://cdn.artofpkm.com/neh6rgjtljhd5262m0pyilvftpt0"
   ],
   "aliases": [
    "swshp-SWSH185"
   ]
  },
  {
   "id": "apkm-476-29",
   "name": "Stunfisk",
   "set": "Paradigm Trigger",
   "number": "029/098",
   "rarity": "Common",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/476/card/29",
   "thumb": "https://cdn.artofpkm.com/tbmdwsrpzejc60ow4a67kf8wabvl",
   "images": [
    "https://cdn.artofpkm.com/kzfghfjz8ahcyrm37qrqc19c549g",
    "https://cdn.artofpkm.com/tbmdwsrpzejc60ow4a67kf8wabvl"
   ],
   "aliases": [
    "swsh12-55",
    "swsh12-055"
   ]
  },
  {
   "id": "apkm-476-44",
   "name": "Beheeyem",
   "set": "Paradigm Trigger",
   "number": "044/098",
   "rarity": "Uncommon",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/476/card/44",
   "thumb": "https://cdn.artofpkm.com/36jwztyhjmmksvt23y16nrn8cazc",
   "images": [
    "https://cdn.artofpkm.com/f8tbzeq3jiumzsf1zfvcb9o7ibn8",
    "https://cdn.artofpkm.com/36jwztyhjmmksvt23y16nrn8cazc"
   ],
   "aliases": [
    "swsh12-80",
    "swsh12-080"
   ]
  },
  {
   "id": "apkm-466-43",
   "name": "Hypno",
   "set": "Lost Abyss",
   "number": "043/100",
   "rarity": "Uncommon",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/466/card/43",
   "thumb": "https://cdn.artofpkm.com/n381cwv2akwv6j5qs6ssz5cttxyz",
   "images": [
    "https://cdn.artofpkm.com/4wyd44pjlb2upjsrv1sdj5qbrm7x",
    "https://cdn.artofpkm.com/n381cwv2akwv6j5qs6ssz5cttxyz"
   ],
   "aliases": [
    "swsh12-61",
    "swsh12-061"
   ]
  },
  {
   "id": "apkm-466-111",
   "name": "Giratina V",
   "set": "Lost Abyss",
   "number": "111/100",
   "rarity": "Super Rare",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/466/card/111",
   "thumb": "https://cdn.artofpkm.com/yl9gl59x20sgve50l9cabir2xgux",
   "images": [
    "https://cdn.artofpkm.com/kpwzapjev02b7t4qkj3gzd5ro0pr",
    "https://cdn.artofpkm.com/yl9gl59x20sgve50l9cabir2xgux"
   ],
   "aliases": [
    "swsh11-186"
   ]
  },
  {
   "id": "apkm-459-40",
   "name": "Ariados",
   "set": "Time Gazer",
   "number": "040/067",
   "rarity": "Uncommon",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/459/card/40",
   "thumb": "https://cdn.artofpkm.com/n3nwxp9k29b7o14kz5qk36o4fp50",
   "images": [
    "https://cdn.artofpkm.com/jdl9wf8c7uf3tskwoj8qs896ecov",
    "https://cdn.artofpkm.com/n3nwxp9k29b7o14kz5qk36o4fp50"
   ],
   "aliases": [
    "swsh11-113"
   ]
  },
  {
   "id": "apkm-460-49",
   "name": "Bronzong",
   "set": "Space Juggler",
   "number": "049/067",
   "rarity": "Uncommon",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/460/card/49",
   "thumb": "https://cdn.artofpkm.com/waz3cany9t1mvluhwq9l77mbkt3n",
   "images": [
    "https://cdn.artofpkm.com/gexnzwcn3le7bm3r6amr8grt412c",
    "https://cdn.artofpkm.com/waz3cany9t1mvluhwq9l77mbkt3n"
   ],
   "aliases": [
    "swsh10-112"
   ]
  },
  {
   "id": "apkm-456-37",
   "name": "Whiscash",
   "set": "Battle Region",
   "number": "022/067",
   "rarity": "Uncommon",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/456/card/37",
   "thumb": "https://cdn.artofpkm.com/zqgevrmnbbtkmas126m111iv2q53",
   "images": [
    "https://cdn.artofpkm.com/tq5dog7yxzfc00t8uv4id93sogc0",
    "https://cdn.artofpkm.com/zqgevrmnbbtkmas126m111iv2q53"
   ],
   "aliases": [
    "swsh10-36",
    "swsh10-036"
   ]
  },
  {
   "id": "apkm-630-16",
   "name": "Whiscash",
   "set": "Poké Ball Mirror",
   "number": "022/067",
   "rarity": "Uncommon",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/630/card/16",
   "thumb": "https://cdn.artofpkm.com/8arrdsvx8qwy2ykl5gm0te0y3q0q",
   "images": [
    "https://cdn.artofpkm.com/b6tpdllq3i6pofxlbcmxeayt6i1g",
    "https://cdn.artofpkm.com/8arrdsvx8qwy2ykl5gm0te0y3q0q"
   ]
  },
  {
   "id": "apkm-453-16",
   "name": "Magmar",
   "set": "Star Birth",
   "number": "016/100",
   "rarity": "Common",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/453/card/16",
   "thumb": "https://cdn.artofpkm.com/nd1ko68bd5h1gvyx19x9ourqdmux",
   "images": [
    "https://cdn.artofpkm.com/62d8mo71w1izpnsyed1gx1qbfbn8",
    "https://cdn.artofpkm.com/nd1ko68bd5h1gvyx19x9ourqdmux"
   ],
   "aliases": [
    "swsh9-19",
    "swsh9-019"
   ]
  },
  {
   "id": "apkm-453-57",
   "name": "Sawk",
   "set": "Star Birth",
   "number": "057/100",
   "rarity": "Common",
   "game": "TCG",
   "url": "https://www.artofpkm.com/sets/453/card/57",
   "thumb": "https://cdn.artofpkm.com/raxcn6h6fbb02b0y8hhjehe0rka9",
   "images": [
    "https://cdn.artofpkm.com/r6lqq9pz2oyehewlp0670f0toqbc",
    "https://cdn.artofpkm.com/raxcn6h6fbb02b0y8hhjehe0rka9"
   ],
   "aliases": [
    "swsh9-81",
    "swsh9-081"
   ]
  },
  {
   "id": "apkm-622-27",
   "name": "Team Rocket’s Drowzee",
   "set": "Team Rocket’s Ambition",
   "number": "027/110",
   "rarity": "One Diamond",
   "game": "Pocket",
   "url": "https://www.artofpkm.com/sets/622/card/27",
   "thumb": "https://cdn.artofpkm.com/4a58v55huxmygf1anggy1i4fuz6t",
   "images": [
    "https://cdn.artofpkm.com/4qsugt67e4btf0fa9urw5kv5frqb",
    "https://cdn.artofpkm.com/4a58v55huxmygf1anggy1i4fuz6t"
   ]
  },
  {
   "id": "apkm-618-67",
   "name": "Hypno",
   "set": "Ruler of the Skies",
   "number": "067/233",
   "rarity": "Two Diamonds",
   "game": "Pocket",
   "url": "https://www.artofpkm.com/sets/618/card/67",
   "thumb": "https://cdn.artofpkm.com/isn5kx6mfb3s7er0x03e1q1r2paa",
   "images": [
    "https://cdn.artofpkm.com/mh8p90p2z05l8ard1kjkodwjow24",
    "https://cdn.artofpkm.com/isn5kx6mfb3s7er0x03e1q1r2paa"
   ]
  },
  {
   "id": "apkm-615-118",
   "name": "Bronzong",
   "set": "Pulsing Aura",
   "number": "118/234",
   "rarity": "Two Diamonds",
   "game": "Pocket",
   "url": "https://www.artofpkm.com/sets/615/card/118",
   "thumb": "https://cdn.artofpkm.com/1m0nqacg219vlpa5z84yklqfxve5",
   "images": [
    "https://cdn.artofpkm.com/gya5s7unl0okl5ufy93opgpshos2",
    "https://cdn.artofpkm.com/1m0nqacg219vlpa5z84yklqfxve5"
   ]
  },
  {
   "id": "apkm-610-281",
   "name": "Dragalge ex",
   "set": "Mega Rising",
   "number": "281/331",
   "rarity": "Special Art (Two Stars)",
   "game": "Pocket",
   "url": "https://www.artofpkm.com/sets/610/card/281",
   "thumb": "https://cdn.artofpkm.com/d45s5zhcbngiux66349a0qttxuwh",
   "images": [
    "https://cdn.artofpkm.com/qscswu97sb36tzgmqou65ivxb1y8",
    "https://cdn.artofpkm.com/d45s5zhcbngiux66349a0qttxuwh"
   ],
   "aliases": [
    "B1-281"
   ]
  },
  {
   "id": "apkm-607-111",
   "name": "Ariados",
   "set": "Wisdom of Sea and Sky",
   "number": "111/241",
   "rarity": "Two Diamonds",
   "game": "Pocket",
   "url": "https://www.artofpkm.com/sets/607/card/111",
   "thumb": "https://cdn.artofpkm.com/o0u1e5dkv50zxq3flf6np3fsbne9",
   "images": [
    "https://cdn.artofpkm.com/yd42v94h2okc6z41jcs94dmvay65",
    "https://cdn.artofpkm.com/o0u1e5dkv50zxq3flf6np3fsbne9"
   ],
   "aliases": [
    "A4-111"
   ]
  },
  {
   "id": "apkm-607-207",
   "name": "Crobat ex",
   "set": "Wisdom of Sea and Sky",
   "number": "207/241",
   "rarity": "Special Art (Two Stars)",
   "game": "Pocket",
   "url": "https://www.artofpkm.com/sets/607/card/207",
   "thumb": "https://cdn.artofpkm.com/qgij3nlmpsvfhl1l1ha8vb4l1gl7",
   "images": [
    "https://cdn.artofpkm.com/orxc6p35olyqguyoh42uc6cv506h",
    "https://cdn.artofpkm.com/qgij3nlmpsvfhl1l1ha8vb4l1gl7"
   ],
   "aliases": [
    "A4-207"
   ]
  },
  {
   "id": "apkm-606-39",
   "name": "Whiscash",
   "set": "Eevee Grove",
   "number": "039/107",
   "rarity": "Two Diamonds",
   "game": "Pocket",
   "url": "https://www.artofpkm.com/sets/606/card/39",
   "thumb": "https://cdn.artofpkm.com/8iquu4lha0egfx3phpz0b6k3qwli",
   "images": [
    "https://cdn.artofpkm.com/zrnjlv5fdbpjvjpngxwwmlj5oj09",
    "https://cdn.artofpkm.com/8iquu4lha0egfx3phpz0b6k3qwli"
   ],
   "aliases": [
    "A3b-039"
   ]
  },
  {
   "id": "apkm-604-176",
   "name": "Drampa",
   "set": "Celestial Guardians",
   "number": "176/155",
   "rarity": "One Star",
   "game": "Pocket",
   "url": "https://www.artofpkm.com/sets/604/card/176",
   "thumb": "https://cdn.artofpkm.com/p3yi4lr80jqyh4xuk2v69766dxp7",
   "images": [
    "https://cdn.artofpkm.com/2kxguq9n5he6ewsfbhfx9n9znw14",
    "https://cdn.artofpkm.com/p3yi4lr80jqyh4xuk2v69766dxp7"
   ],
   "aliases": [
    "A3-176"
   ]
  },
  {
   "id": "apkm-603-96",
   "name": "Giratina ex",
   "set": "Shining Revelry",
   "number": "096/072",
   "rarity": "Immersive (Three Stars)",
   "game": "Pocket",
   "url": "https://www.artofpkm.com/sets/603/card/96",
   "thumb": "https://cdn.artofpkm.com/e3nwdc2bnatpehalx7t368twkjwk",
   "images": [
    "https://cdn.artofpkm.com/tf770fzry2m6o18fvsan54rt7cl4",
    "https://cdn.artofpkm.com/e3nwdc2bnatpehalx7t368twkjwk"
   ],
   "aliases": [
    "A2b-096"
   ]
  },
  {
   "id": "apkm-601-172",
   "name": "Spiritomb",
   "set": "Space-Time Smackdown",
   "number": "172/155",
   "rarity": "One Star",
   "game": "Pocket",
   "url": "https://www.artofpkm.com/sets/601/card/172",
   "thumb": "https://cdn.artofpkm.com/prb99cdugvrrwcezk8mj2zgxjrbg",
   "images": [
    "https://cdn.artofpkm.com/6hrqz4512mlcoidp1rex9hsvp4n3",
    "https://cdn.artofpkm.com/prb99cdugvrrwcezk8mj2zgxjrbg"
   ],
   "aliases": [
    "A2-172"
   ]
  }
 ]
};
