#!/usr/bin/env python3
"""Build cards.js (the bundled card list) from an artofpkm.com illustrator page.

The binder then lists exactly the cards the site lists for that illustrator,
in the same order and with the site's card images.

Usage:
  python3 tools/build_artofpkm.py shinji-kanda "Shinji Kanda" [old-cards.js] > cards.js

The illustrator slug is the one in https://www.artofpkm.com/illustrators/<slug>/cards.
Each card's detail page is also fetched for its rarity.

If an older cards.js is given, its card ids are kept as aliases on the matching
new card (same Pokémon, same game), so marks saved with an older list carry over.
"""
import html
import json
import re
import sys
import time
import urllib.request

SITE = "https://www.artofpkm.com"


def get(url):
    for attempt in range(4):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (binder card list builder)"})
            with urllib.request.urlopen(req, timeout=30) as r:
                return r.read().decode("utf-8")
        except Exception:
            if attempt == 3:
                raise
            time.sleep(2 ** attempt)


def text(s):
    return " ".join(html.unescape(re.sub(r"<[^>]+>", " ", s or "")).split())


def parse_list(page):
    """Cards in page order. Section headers ("TCG (45)", "Pocket (10)") set the game."""
    cards, game = [], None
    pattern = r'<summary[^>]*>(.*?)</summary>|<a data-action="click-&gt;lightbox#open"(.*?)</a>'
    for m in re.finditer(pattern, page, re.S):
        if m.group(1) is not None:
            head = re.match(r"(.+?) \(\d+\)$", text(m.group(1)))
            if head:
                game = head.group(1)
            continue
        a = m.group(2)
        attr = lambda p: (re.search(p, a, re.S) or [None, None])[1]
        url = attr(r'href="(/sets/\d+/card/\d+)"')
        number, set_name = [text(x) for x in re.findall(r'card-subtitle[^>]*>(.*?)</div>', a)][:2]
        cards.append({
            "url": url,
            "name": text(attr(r'card-title[^>]*>(.*?)</div>')),
            "set": set_name,
            "number": number,
            "game": game,
            "big": attr(r'data-lightbox-src="([^"]+)"'),
            "thumb": attr(r'<img[^>]*src="([^"]+)"'),
        })
    return cards


def rarity_of(detail):
    m = re.search(r'href="/rarities/\d+">(?:<img[^>]*>)?([^<]+)</a>', detail)
    return text(m.group(1)) if m else ""


def old_cards(path):
    src = open(path, encoding="utf-8").read()
    return json.loads(src[src.index("] = ") + 4:].rstrip().rstrip(";"))["cards"]


def add_aliases(cards, old):
    """Give each old id to the first new card (oldest print first) with the same name and game."""
    taken = set()
    for o in old:
        game = "TCG" if o["game"].startswith("TCG") else o["game"]
        matches = [c for c in reversed(cards) if c["name"] == o["name"] and c["game"] == game]
        matches.sort(key=lambda c: "Mirror" in c["set"])  # the original print over a mirror reprint
        # Prefer a print not already claimed, so reprints of one artwork map one to one.
        pick = next((c for c in matches if c["id"] not in taken), matches[0] if matches else None)
        if pick:
            taken.add(pick["id"])
            pick.setdefault("aliases", []).extend([o["id"], *o.get("aliases", [])])


def main():
    if len(sys.argv) not in (3, 4):
        sys.exit(__doc__)
    slug, artist = sys.argv[1], sys.argv[2]
    listed = parse_list(get(f"{SITE}/illustrators/{slug}/cards"))
    if not listed:
        sys.exit("No cards found on the page")

    cards = []
    for c in listed:
        set_id, num = re.match(r"/sets/(\d+)/card/(\d+)", c["url"]).groups()
        cards.append({
            "id": f"apkm-{set_id}-{num}",
            "name": c["name"],
            "set": c["set"],
            "number": c["number"],
            "rarity": rarity_of(get(SITE + c["url"])),
            "game": c["game"],
            "url": SITE + c["url"],
            "thumb": c["thumb"],
            "images": [c["big"], c["thumb"]],
        })
    if len(sys.argv) == 4:
        add_aliases(cards, old_cards(sys.argv[3]))

    payload = {"artist": artist, "source": f"{SITE}/illustrators/{slug}/cards", "cards": cards}
    print("// Generated by tools/build_artofpkm.py. Do not edit by hand.")
    print("window.BINDER_DATA = window.BINDER_DATA || {};")
    print(f"window.BINDER_DATA[{json.dumps(artist.lower())}] = "
          + json.dumps(payload, ensure_ascii=False, indent=1) + ";")


if __name__ == "__main__":
    main()
